export enum MenuWarehouseEum {
  DASHBOARD = 'DASHBOARD',
  PRODUCT = 'PRODUCT',
  CONTAINER = 'CONTAINER',
  IOI_RECEIPT = 'IOI_RECEIPT',
  PROVIDER = 'PROVIDER',
  IMPORT_EXPORT = 'IMPORT_EXPORT',
  REVENUE = 'REVENUE',
  ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT',
}
