export enum WarehouseTypeEnum{
  MEDICINE = 'MEDICINE',
  APPLIANCES = 'APPLIANCES',
  MAIN_WAREHOUSE = 'MAIN_WAREHOUSE',
  POULTRY_FOOD = 'POULTRY_FOOD',
  PRODUCT = 'PRODUCT',
  REQUISITE = 'REQUISITE',
}
