export enum WarehouseTypeEnum{
  MEDICINE = 'MEDICINE',
  APPLIANCE = 'APPLIANCE',
  MAIN_WAREHOUSE = 'MAIN_WAREHOUSE',
  POULTRY_FOOD = 'POULTRY_FOOD',
  PRODUCT = 'PRODUCT',
  REQUISITE = 'REQUISITE',
}
