export enum FilterSalaryEnum {
  TITLE = 'TITLE',
  TITLE_SETTING = 'TITLE_SETTING',
  DATETIME = 'DATETIME',
  DURATION = 'DURATION',
  TYPE = 'TYPE',
  DATETIME_SETTING = 'DATETIME_SETTING',
  RATE_SETTING = 'RATE_SETTING',
}
