export enum UpdateEmployeeEnum {
  GENERAL_INFO = 'GENERAL_INFO',
  IDENTITY = 'IDENTITY',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  ACADEMIC_LEVEL = 'ACADEMIC_LEVEL',
  CONTACT_INFO = 'CONTACT_INFO',
  CONTACT_SOS = 'CONTACT_SOS',
}
