export enum MenuAdminEnum {
  OVERVIEW = 'OVERVIEW',
  OVERVIEW_SELL = 'OVERVIEW_SELL',
  OVERVIEW_WAREHOUSE = 'OVERVIEW_WAREHOUSE',
  OVERVIEW_PERSONNEL = 'OVERVIEW_PERSONNEL',
  OVERVIEW_FINANCE = 'OVERVIEW_FINANCE',
}
