export enum SalaryTypeEnum {
  BASIC = 'BASIC',
  BASIC_INSURANCE = 'BASIC_INSURANCE',
  STAY = 'STAY',
  ALLOWANCE = 'ALLOWANCE',
  OVERTIME = 'OVERTIME',
  ABSENT = 'ABSENT',
  EARLY = 'EARLY',
  LATE = 'LATE',
  BASIC_TRUST = 'BASIC_TRUST'
}
