export const Api = {
  AUTH: 'auth/signin',
  ORG_CHART: 'org-chart',
  BRANCH: 'branch',
  DEPARTMENT: 'department',
  POSITION: 'position',
  EMPLOYEE: 'employee',
  PAYROLL: 'payroll',
  SALARY: 'salary',
  RELATIVE: 'relative',
  DEGREE: 'degree',
  Payroll:'payroll',
  template_OVERTIME: 'overtime-template',
  CUSTOMER:'customer',
  COMMODITY:'commodity',
  ORDER: 'order',
  ROUTE: 'route',
};
