export const Api = {
  AUTH: 'auth/signin',
  ORG_CHART: 'org-chart',
  BRANCH: 'branch',
  DEPARTMENT: 'department',
  POSITION: 'position',
  EMPLOYEE: 'employee',
  PAYROLL: 'payroll',
  SALARY: 'salary',
  RELATIVE: 'relative',
  DEGREE: 'degree',
  Payroll:'payroll',
  template_OVERTIME: 'overtime-template',
  holiday: 'holiday',
  CUSTOMER:'customer',
  PAYMENT:'payment',
  COMMODITY:'commodity',
  ORDER: 'order',
  ROUTE: 'route',
  BILL: 'bill',
  NATION: 'nation',
  PROVINCE: 'province',
  DISTRICT: 'district',
  WARD: 'ward',
  STATISTICAL_AGENCY: 'statistical/agency',
  STATISTICAL_PROVINCE: 'statistical/nation',
  STATISTICAL_CHICKEN: 'statistical/chicken',
};
