import { Requisite } from '../../apps/warehouse/src/app/child-dashboard/requisite-dashboard/+state/requisite .interface';

export const FeatureName = {
  AUTH: 'auth',
  BRANCH: 'branch',
  ORG_CHART: 'orgchart',
  EMPLOYEE: 'employee',
  PAYROLL: 'payroll',
  DEPARTMENT: 'department',
  POSITION: 'position',
  TEMPLATE_OVERTIME :'template_overtime',
  HOLIDAY :'holiday',
  CUSTOMER: 'customer',
  PAYMENT: 'payment',
  COMMODITY: 'commodity',
  ORDER : 'order',
  ROUTE : 'route',
  BILL : 'bill',
  NATION : 'nation',
  PROVINCE : 'province',
  DISTRICT : 'district',
  WARD : 'ward',
  MEDICINE: 'medicine',
  PRODUCT: 'product',
  APPLIANCE: 'appliance',
  POULTRY_FOOD: 'poultryFood',
  REQUISITE: 'requisite',
};
