

export const FeatureName = {
  AUTH: 'auth',
  BRANCH: 'branch',
  ORG_CHART: 'orgchart',
  EMPLOYEE: 'employee',
  PAYROLL: 'payroll',
  DEPARTMENT: 'department',
  POSITION: 'position',
  TEMPLATE_OVERTIME :'template overtime',
  TEMPLATE_SALARY :'template salary',
  HOLIDAY :'holiday',
  CUSTOMER: 'customer',
  PAYMENT: 'payment',
  COMMODITY: 'commodity',
  ORDER : 'order',
  ORDER_ASSIGNED : 'orderAssigned',
  ROUTE : 'route',
  BILL : 'bill',
  NATION : 'nation',
  PROVINCE : 'province',
  DISTRICT : 'district',
  WARD : 'ward',
  SYSTEM_HISTORY : 'systemHistory',
  MAIN: 'main',
  OVERTIME: 'overtime',
  ACCOUNT: 'account',
  ADMIN: 'admin',
  WAREHOUSE: 'category',
};
