export const FeatureName = {
  AUTH: 'auth',
  BRANCH: 'branch',
  ORG_CHART: 'orgchart',
  EMPLOYEE: 'employee',
  PAYROLL: 'payroll',
  DEPARTMENT: 'department',
  POSITION: 'position',
  TEMPLATE_OVERTIME :'template_overtime',
  HOLIDAY :'holiday',
  CUSTOMER: 'customer',
  COMMODITY: 'commodity',
  ORDER : 'order',
  ROUTE : 'route',
  BILL : 'bill',
  NATION : 'nation',
  PROVINCE : 'province',
  DISTRICT : 'district',
  WARD : 'ward',
  WAREHOUSE: 'warehouse'
};
