export enum MenuEnum {
  HOME = 'HOME',
  ORDER = 'ORDER',
  CUSTOMER = 'CUSTOMER',
  ROUTE = 'ROUTE',
  SYSTEM_HISTORY = 'SYSTEM_HISTORY',
  COMMODITY_TEMPLATE = 'COMMODITY_TEMPLATE',
  WAREHOUSE_SUPPLIES = 'WAREHOUSE_SUPPLIES',
  OVERVIEW_SELL = 'OVERVIEW_SELL',
  OVERVIEW = 'OVERVIEW',
  ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT',
  PROVIDER = 'PROVIDER',
  REVENUE = 'REVENUE',
}
