export enum MenuEnum {
  HOME = 'HOME',
  ORDER = 'ORDER',
  CUSTOMER = 'CUSTOMER',
  ROUTE = 'ROUTE',
  SYSTEM_HISTORY = 'SYSTEM_HISTORY',
  WAREHOUSE_SUPPLIES = 'WAREHOUSE_SUPPLIES',
  OVERVIEW_SELL = 'OVERVIEW_SELL',
  OVERVIEW = 'OVERVIEW',
  OVERVIEW_WAREHOUSE = 'OVERVIEW_WAREHOUSE',
  OVERVIEW_PERSONNEL = 'OVERVIEW_PERSONNEL',
  OVERVIEW_FINANCE = 'OVERVIEW_FINANCE',
  DASHBOARD = 'DASHBOARD',
  ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT',
  PROVIDER = 'PROVIDER',
  IMPORT_EXPORT = 'IMPORT_EXPORT',
  REVENUE = 'REVENUE'
}
