export enum OrderEnum {
  END = 'END',
  CUSTOMER = "CUSTOMER",
  CREATED_AT = "CREATED_AT",
  PROVINCE = "PROVINCE",
  TOTAL_AMOUNT_COMMODITY = "TOTAL_AMOUNT_COMMODITY",
  TOTAL_COMMODITIES = "TOTAL_COMMODITIES",
  PAYMENT = "PAYMENT",
  AMOUNT_PAYMENT = "AMOUNT_PAYMENT",
  EXPLAIN = "EXPLAIN",
}
