export enum ItemContextMenu {
  PERMANENTLY = 'PERMANENTLY',
  RESTORE = 'RESTORE',
  DETAIL = 'DETAIL',
  PAYMENT = 'PAYMENT',
  ENDED_AT = 'ENDED_AT',
  HISTORY_PAYROLL = 'HISTORY_PAYROLL',
  PROFILE = 'PROFILE',
  PAYROLL = 'PAYROLL',
  OVERTIME = 'OVERTIME',
  POSITIONS = 'POSITIONS',
  ADD_ORDER = 'ADD_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
}
