export enum PageTypeEnum {
  CUSTOMER = 'CUSTOMER',
  ORDER = 'ORDER',
  HISTORY_PAYROLL = 'HISTORY_PAYROLL',
  PAYMENT_HISTORY = 'PAYMENT_HISTORY',
  EMPLOYEE_LEFT_AT = 'EMPLOYEE_LEFT_AT',
  ACCOUNT = 'ACCOUNT',
  PAYROLL = 'PAYROLL',
  BRANCH = 'BRANCH',
  POSITION = 'POSITION',
  PAYROLL_OVERTIME = 'PAYROLL_OVERTIME',
  PAYROLL_SALARY = 'PAYROLL_SALARY',
}
