export enum StatisticalYType{
  CUSTOMER ='CUSTOMER',
  ORDER ='ORDER',
  REVENUE ='REVENUE',
  POTENTIAL = 'POTENTIAL',
  COMMODITY = 'COMMODITY',
  COMMODITY_DETAIL = 'COMMODITY_DETAIL',
  DEBT = 'DEBT'
}

export enum StatisticalXType {
  PROVINCE ='PROVINCE',
  AGENCY ='AGENCY',
  CHICKEN_TYPE ='CHICKEN_TYPE',
}
