export enum InputSearchEnum {
  NAME = 'name',
  CODE = 'code',
  POSITION = 'position',
  BRANCH = 'branch',
  CREATED_AT = 'createdAt',
  WORKDAY = 'workday',
  ACTUAL_DAY = 'actualDay',
  WORK_DAY_NOT_IN_HOLIDAY = 'workdayNotInHoliday',
  WORKS_IN_HOLIDAY = 'worksInHoliday',
  WORKS_NOT_IN_HOLIDAY = 'worksNotInHoliday',
  WORKS_OVERTIME_DAY = 'workOvertimeDay',
  ABSENT_DAY = 'absentDay',
  TOTAL_WORK_DAY = 'totalWorkday',
  BASIC = 'basic',
  STAY = 'stay',
  ALLOWANCE = 'allowance',
  OVERTIME = 'overtime',
  PAYSLIP_IN_HOLIDAY = 'payslipInHoliday',
  PAYSLIP_IN_NOT_HOLIDAY = 'payslipNotInHoliday',
  DEDUCTION = 'deduction',
  TAX = 'tax',
  TOTAL = 'total'
}
