export enum FilterTypeEnum {
  PAYROLL = 'PAYROLL',
  TIME_SHEET = 'TIME_SHEET',
  SALARY  = 'SALARY',
  SEASONAL = 'SEASONAL ',
  OVERTIME = 'OVERTIME',
  BASIC = 'BASIC',
  STAY = 'STAY',
  ALLOWANCE = 'ALLOWANCE',
  ABSENT = 'ABSENT',
}
