export enum FilterTypeEnum {
  PAYROLL = 'PAYROLL',
  TIME_SHEET = 'TIME_SHEET',
  SEASONAL = 'SEASONAL',
  OVERTIME = 'OVERTIME',
  BASIC = 'BASIC',
  STAY = 'STAY',
  ALLOWANCE = 'ALLOWANCE',
  ABSENT = 'ABSENT',
  PERMANENT = 'PERMANENT',
}
