export enum PayrollEnum {
  PAYROLL = 'PAYROLL',
  PAYROLL_OVERTIME = 'PAYROLL_OVERTIME',
  TIME_SHEET = 'TIME_SHEET',
  PAYROLL_SEASONAL = 'PAYROLL_SEASONAL',
  PAYROLL_BASIC = 'PAYROLL_BASIC',
  PAYROLL_STAY = 'PAYROLL_STAY',
  PAYROLL_ALLOWANCE = 'PAYROLL_ALLOWANCE',
}
